### ISSUE TITLE
Add option for reset users

### ISSUE THREAD

**Issue by matsuyoshi30** [matsuyoshi30/gitsu#4]

**Comment by Techassi** [comment]
I have time to implement this functionality with a PR. 

Just to be sure: what exactly dou you mean by `resetting` users? Do you want to reset the saved users in the `config.json` file or do you want to unset the user via `git config --local / --global`?

**Comment by Threpio** [comment]
I would interpret this to be a reset of the different gitsu user profiles :)

A workflow like the following:

`git su`

`Reset git users in gitsu`

`Are you sure you want to remove users {alias1}, {alias2} and {alias3}?`
`No`
`Yes`

**Comment by Techassi** [comment]
Makes sense...

I could also see the following (adjusted) workflow:

```shell
gitsu reset
```

```shell
Are you sure you want to remove <number of users> user profile(s)?
  [alias1] Foo <bar@baz.com>
  [alias2] LazyDog <example@example.com>
(y)es/(N)o
```

or a more user controllable approach like:

```shell
Select user profile(s) you want to delete (Space to select, enter to confirm):
> [ ] [alias1] Foo <bar@baz.com>
  [X] [alias2] LazyDog <example@example.com>
```

Let me know what you think about both approaches!

PS: The second approach would require the use of a different prompt library (instead of https://github.com/manifoldco/promptui) as it does not support multiselect prompts. https://github.com/AlecAivazis/survey might be a fitting alternative.

**Comment by matsuyoshi30** [comment]
Ahhhh sorry for the delayed reaction.

I think it becomes more convenient to be able to reset all of the saved users, so it would be nice like:

```
Are you sure you want to remove <number of users> user profile(s)?
  [alias1] Foo <bar@baz.com>
  [alias2] LazyDog <example@example.com>
(y)es/(N)o
```

**Comment by Techassi** [comment]
Okay...

Currently working on another PR (for this project), but I will include this feature asap.
